config/routes.rb
Rails.application.routes.draw do
  root 'lists#index'
  get '/search_field' => 'search#index'
  get '/search' => 'search#search'
  resources :lists, only: [:index, :create] do
    resources :todos, only: [:index, :create, :update]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/list.rb
class List < ApplicationRecord
  has_many :todos
  validates :name, presence: true
  validates :name, length: { maximum: 30 }
end

app/models/todo.rb
class Todo < ApplicationRecord
  belongs_to :list
  validates :body, :limit, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController

  before_action :set_lists

  def index
    @list = List.new
  end

  def create
    @list = List.new(list_params)
    if @list.save
      redirect_to root_path
      flash[:notice] = '新しいTodoリスト作成されました'
    else
      render :index
    end
  end

  private

  def list_params
    params.require(:list).permit(:name)
  end

  def set_lists
    @lists = List.order("created_at DESC").all
  end
end

app/controllers/search_controller.rb
class SearchController < ApplicationController

  def index
  end

  def search
    @todo_results = Todo.where('body LIKE(?)', "%#{params[:input]}%")
    @list_results = List.where('name LIKE(?)', "%#{params[:input]}%")
    respond_to do |format|
      format.json
    end
  end
end

app/controllers/todos_controller.rb
class TodosController < ApplicationController

  before_action :set_list, :set_todos

  def index
    @todo = Todo.new
  end

  def create
    @todo = Todo.new(todo_params)
    if @todo.save
      redirect_to list_todos_path(@list)
    else
      render :index
    end
  end

  def update
    @todo = Todo.find(params[:id])
    if params[:state] == "1"
      @todo.update(state: 2)
    else
      @todo.update(state: 1)
    end
  end

  private

  def todo_params
    params.require(:todo).permit(:body, :limit, :state).merge(list_id: params[:list_id])
  end

  def set_list
    @list = List.find(params[:list_id])
  end

  def set_todos
    @todos = List.find(params[:list_id]).todos.order('created_at DESC')
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/helpers/search_helper.rb
module SearchHelper
end

app/helpers/todos_helper.rb
module TodosHelper
end

app/views/common/_error.html.erb
<ul class='error_messages_lists'>
  <% notice.errors.full_messages.each do |err| %>
    <li class='error_message_list'>
      <p class='error_message'><%= err %></p>
    </li>
  <% end %>
</ul>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TodoApp</title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header class='clearfix'>
      <div class='root_path_logo'>
        <%= link_to 'Todoリスト', root_path %>
      </div>
      <div class='search_path_logo'>
        <%= link_to '検索', search_field_path %>
      </div>
    </header>
    <%= yield %>
  </body>
</html>

app/views/lists/_flash.html.erb
<% flash.each do |key, value| %>
  <%= content_tag(:div, value, class: "#{key}") %>
<% end %>

app/views/lists/_list.html.erb
<% lists.each do |list| %>
  <li class='list'>
    <div class='list--detail'>
      <p class='list--detail__name'>
        <%= link_to "#{ list.name }", list_todos_path(list), class: 'list--detail__name__path' %>
      </p>
      <p class='list--detail__todo'>todoがありません</p>
    </div>
  </li>
<% end %>

app/views/lists/index.html.erb
<main>
  <div class='main__content'>
    <%= form_for @list do |f| %>
      <div class='new_list--input'>
        <%= f.label :name, '新しいリストを作成する', class: 'new_list--input--label' %><br>
          <%= f.text_field :name, class: 'new_list--input--name', placeholder: 'リスト名を入力してください' %>
        <%= f.submit 'リストの作成', id: 'input_box' %>
      </div>
    <% end %>
    <% if @list.errors.any? %>
      <%= render 'common/error', notice: @list %>
    <% end %>
    <%= render 'flash' %>
    <div class='main__lists'>
      <ul class='lists'>
        <% if @lists.exists? %>
          <%= render 'list', lists: @lists %>
        <% else %>
          <div class='no_list'>
            登録されているTodoリストがありません
          </div>
        <% end %>
      </ul>
    </div>
  </div>
</main>

app/views/search/index.html.erb
<div class='search__field'>
  <div class='search__box'>
    <input type='text' class='search__box--text' id='search-input'>
    <button type='submit' class='search__box--submit' id='search-button'>検索</button>
  </div>
</div>
<div class='result__field'>
  <ul class='result__todos'>
  </ul>
  <ul class='result__lists'>
  </ul>
</div>

app/views/todos/_todo.html.erb
<% todos.each do |todo| %>
  <div class='todo__contents clearfix' id='todo__<%= todo.id %>' data-id=<%= todo.id %>>
    <p id='todo_content_name'><%= todo.body %></p>
    <ul class='todo__lists'>
      <li class='todo__lists__limit clearfix'>
        <p class='todo__lists__limit--label'>期限:</p>
        <p class='todo__lists__limit--content'><%= l todo.limit, format: :long %></p>
      </li>
      <li class='todo__lists__created clearfix'>
        <p class='todo__lists__created--label'>作成日:</p>
        <p class='todo__lists__created--content'><%= l todo.created_at, format: :long %></p>
      </li>
    </ul>
    <% if todo.state == 1 %>
      <div id='button--<%= todo.id %>' class='no__complete__button state__button' data-state=<%= todo.state %>>
        <p id='state'>未完了</p>
      </div>
    <% else %>
      <div id='button--<%= todo.id %>' class='complete__button state__button' data-state=<%= todo.state %>>
        <p id='state'>完了</p>
      </div>
    <% end %>
  </div>
<% end %>

app/views/todos/index.html.erb
<div class='main'>
  <div class='todo__detail' data-list-id=<%= @list.id %>>
    <h1 class='todo__detail__name'><%= @list.name %></h1>
    <%= form_for [@list,@todo] do |f| %>
      <p id='form__description'>新しいTodoを作成する</p>
      <ul class='new_todo__detail--form'>
        <li class='new_todo__detail--form__input'>
          <%= f.label :body, 'Todo名', class: 'new_todo__detail--form__input__label' %>
          <%= f.text_field :body, class: 'new_todo__detail--form__input__text', placeholder: 'Todo名を入力してください' %>
        </li>
        <li class='new_todo__detail--form__input'>
          <%= f.label :limit, '期限', class: 'new_todo__detail--form__input__label' %>
          <%= f.text_field :limit, class: 'new_todo__detail--form__input__text', placeholder: '例) 2017年8月10日 => 2017-08-09 or 20170809' %>
          <%= f.hidden_field :state, value: 1 %>
          <%= f.submit 'Todoの追加', id: 'submit_button' %>
        </li>
      </ul>
    <% end %>
    <% if @todo.errors.any? %>
      <%= render 'common/error', notice: @todo %>
    <% end %>
  </div>
  <% if @todos.exists? %>
    <%= render 'todo', todos: @todos %>
  <% else %>
    <div class='no_todo_list'>
      登録されたTodoはございません。
    </div>
  <% end %>
</div>